// GIF ACTIONS
export const GET_GIPHY = 'GET_GIPHY';
export const GET_GIPHY_CATEGORIES = 'GET_GIPHY_CATEGORIES';
export const GET_GIPHY_SEARCH_SUGGESTIONS = 'GET_GIPHY_SEARCH_SUGGESTIONS';
export const TYPE_OF_GIF_API = 'TYPE_OF_GIF_API';

// API CALLING
export const API_SUCCESS = 'API_SUCCESS';
export const API_REQUEST = 'API_REQUEST';
export const API_LIST_END = 'API_LIST_END';
export const API_FAILURE = 'API_FAILURE';

// theme
export const THEME_TOGGLER = 'THEME_TOGGLER';
